require File.join( File.dirname(__FILE__), 'lib/template')
require File.join( File.dirname(__FILE__), 'lib/token')
require File.join( File.dirname(__FILE__), 'lib/tokenizer')
require File.join( File.dirname(__FILE__), 'lib/learner')
require File.join( File.dirname(__FILE__), 'lib/extracter')